### ISSUE TITLE
Every 3rd-5th edit page load, javascript is not initialised and widgets don't appear

### ISSUE THREAD

**Issue by fredvd** [plone/plone.app.widgets#156]
Using Plone 4.3.14, testing p.a.widgets 1.91. Created a site, installed p.a.widgets in the control panel.

Randomly the following error is shown in the browser console, which disables all widgets richtext-area's, the formtabs for categorisation, etc. from being initialised:

widgets.js:168 Uncaught Error: Mismatched anonymous define() module: function ($) {
"use strict";
 
.... .....

http://requirejs.org/docs/errors.html#mismatch
    at makeError (http://localhost:8080/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.widgets.js:1:1396)
    at intakeDefines (http://localhost:8080/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.widgets.js:1:7745)
    at http://localhost:8080/Plone/portal_javascripts/Sunburst%20Theme/++resource++plone.app.widgets.js:1:16557

**Comment by fredvd** [comment]
- Doing some more checks:

- the error is visible in the console on loading all pages, not just the edit page, so the error might not be related to the widgets not initialising.
- My first tests were when running in debug mode. if I turn debug mode off, the error is still displayed on every page, but the javascript is now always initialised correctly

**Comment by holdenhao** [comment]
Your issue may be related to a bug in plone.app.jquerytools.form.js that I [reported](https://github.com/plone/plone.app.jquerytools/issues/17) for plone.app.jquerytools.

**Comment by fredvd** [comment]
@holdenhao You might want to test plone.app.widgets directly from the 1.x branch on github and not the released 1.9.x versions on pypi.  @thet and @petschki did some work this June in #167 and #168 to avoid collissions between old style javascripts and require.js  . That's what's causing the mismatched anonymous defined error and I think also closes this issue. 

The 1.x branch now has AFAIK very reliable TinyMCE loading also in development mode, I wasn't able to trigger an empty textarea while testing. 

We might need a new 1.9.x release not to disappoint others testing p.a.widgets 1.x in Plone 4, this looks very promising now.

**Comment by holdenhao** [comment]
Thank you for letting me know.  I will test from source.  My temporary fix was to use version 1.9.0 of plone.app.jquerytools
